# Generated by Django 4.2.1 on 2023-05-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sanctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_ID', models.PositiveIntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CARSProject.projects'))),
                ('Installments', models.PositiveSmallIntegerField(default=0)),
                ('Installment_sum', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='id',
        ),
        migrations.AddField(
            model_name='projects',
            name='Nomination_RSP',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='Project_ID',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
