# Generated by Django 4.2.1 on 2023-05-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0002_sanctions_remove_projects_id_projects_nomination_rsp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sanctions',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Interested_institutes',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Project_Buildup',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Start_date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Total_cost',
        ),
        migrations.AddField(
            model_name='projects',
            name='Cluster',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Current_status',
            field=models.CharField(blank=True, default='NA', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Date_of_Start',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Date_of_closure',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Deliveries',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Domain_lab',
            field=models.CharField(default='NA', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Extended_PDC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Final_Cost',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Initial_Sanction_Cost',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='PDC',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Scantion_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Total_Expenditure',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Trained_manpower',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='date_of_Complition',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='no_of_IPR_Filed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='no_of_publications',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Nomination_RSP',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='RSQR',
            field=models.CharField(default='NA', max_length=500, null=True),
        ),
    ]
