# Generated by Django 4.2.1 on 2023-05-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0003_delete_sanctions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='project',
        ),
    ]
