# Generated by Django 4.2.1 on 2023-05-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0004_rename_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_of_Project', models.CharField(blank=True, max_length=500, null=True)),
                ('Cost_in_lakh', models.FloatField(null=True)),
                ('Project_no_Buildup', models.PositiveBigIntegerField(blank=True, null=True)),
                ('Advance_date', models.DateField(auto_now=True, null=True)),
                ('Advnace_amount', models.PositiveIntegerField(null=True)),
                ('DV_no_Cheque_slip_no', models.PositiveIntegerField(null=True)),
                ('Cheque_date', models.DateField(null=True)),
                ('Installment_1_date', models.DateField(null=True)),
                ('Installment_1_amount', models.PositiveIntegerField(null=True)),
                ('Installment_2_date', models.DateField(null=True)),
                ('Installment_2_amount', models.PositiveIntegerField(null=True)),
                ('Installment_3_date', models.DateField(null=True)),
                ('Installment_3_amount', models.PositiveIntegerField(null=True)),
                ('Installment_4_date', models.DateField(null=True)),
                ('Installment_4_amount', models.PositiveIntegerField(null=True)),
                ('cheque_no_date', models.CharField(max_length=500, null=True)),
                ('total_amount_released', models.PositiveIntegerField(null=True)),
                ('unutilized_amount', models.PositiveIntegerField(null=True)),
                ('total_utilized_amount', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
