# Generated by Django 4.2.1 on 2023-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0006_rename_advance_date_payment_advance_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_of_Complition',
            new_name='date_of_complition',
        ),
        migrations.AlterField(
            model_name='payment',
            name='advnace_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='dv_no_cheque_slip_no',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_1_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_2_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_3_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_4_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount_released',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_utilized_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='unutilized_amount',
            field=models.FloatField(null=True),
        ),
    ]
