# Generated by Django 4.2.1 on 2023-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0007_rename_date_of_complition_project_date_of_complition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='final_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_sanction_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_of_IPR_Filed',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_of_publications',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.FloatField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_expenditure',
            field=models.FloatField(default=0, null=True),
        ),
    ]
