# Generated by Django 4.2.1 on 2023-06-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0008_alter_project_final_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='scantion_year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
