# Generated by Django 4.2.1 on 2023-06-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0010_alter_project_extended_pdc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.AddField(
            model_name='project',
            name='Title_of_Project',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='advance_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='advnace_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cheque_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cheque_no_date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_in_lakh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dv_no_cheque_slip_no',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='installment_1_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='installment_1_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='installment_2_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='installment_2_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='installment_3_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='installment_3_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='installment_4_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='installment_4_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_no_buildup',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_amount_released',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_utilized_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='unutilized_amount',
            field=models.FloatField(null=True),
        ),
    ]
