# Generated by Django 4.2.1 on 2023-06-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0011_delete_payment_project_title_of_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gsqr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feild_1', models.CharField(max_length=300)),
                ('Feild_2', models.CharField(max_length=300)),
                ('Feild_3', models.CharField(max_length=300)),
                ('Feild_4', models.CharField(max_length=300)),
            ],
        ),
    ]
