# Generated by Django 4.2.1 on 2023-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0013_remove_project_deliveries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
