# Generated by Django 4.2.1 on 2023-06-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0014_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='extended_pdc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
