# Generated by Django 4.2.1 on 2023-06-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0017_alter_project_date_of_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='rsqr',
            new_name='carsl1selectedinstitutes',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='final_cost',
            new_name='no_of_irsp_Filed',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='no_of_IPR_Filed',
            new_name='total_cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_expenditure',
        ),
        migrations.AddField(
            model_name='project',
            name='carscoordinator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='irsp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
