# Generated by Django 4.2.1 on 2023-06-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0018_rename_rsqr_project_carsl1selectedinstitutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_no_buildup',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
