# Generated by Django 4.2.1 on 2023-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0021_rsqr_delete_gsqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='irsp',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
