# Generated by Django 4.2.1 on 2023-06-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0023_rsqr_chairman_rsqr_member_1_rsqr_member_2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rsqr',
            new_name='irsp',
        ),
    ]
