# Generated by Django 4.2.1 on 2023-06-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0025_delete_irsp_project_chairman_project_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
