# Generated by Django 4.2.1 on 2023-06-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0026_alter_project_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='irsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(blank=True, max_length=225, null=True)),
                ('justification', models.CharField(blank=True, max_length=500, null=True)),
                ('plan_of_work', models.CharField(blank=True, max_length=600, null=True)),
                ('milestones', models.CharField(blank=True, max_length=600, null=True)),
                ('project_investigator', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, max_length=500, null=True)),
                ('chairman', models.CharField(blank=True, max_length=100, null=True)),
                ('member_1', models.CharField(blank=True, max_length=100, null=True)),
                ('member_2', models.CharField(blank=True, max_length=100, null=True)),
                ('member_3', models.CharField(blank=True, max_length=100, null=True)),
                ('member_secretory', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='chairman',
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member_3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member_secretory',
        ),
        migrations.RemoveField(
            model_name='project',
            name='milestones',
        ),
        migrations.RemoveField(
            model_name='project',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='project',
            name='plan_of_work',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_investigator',
        ),
        migrations.AlterField(
            model_name='project',
            name='total_cost',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
