# Generated by Django 4.2.1 on 2023-06-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0028_delete_irsp_project_chairman_project_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='minsheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
