# Generated by Django 4.2.1 on 2023-06-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0029_project_minsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
