# Generated by Django 4.2.1 on 2023-06-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0032_project_annexure_1_project_annexure_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cheque_no_date',
            new_name='Equipment_Issued_at_Installment_1',
        ),
        migrations.AddField(
            model_name='project',
            name='Equipment_Issued_at_Installment_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Equipment_Issued_at_Installment_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Equipment_Issued_at_Installment_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cheque_no_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cheque_no_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cheque_no_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cheque_no_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
