# Generated by Django 4.2.1 on 2023-07-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0033_rename_cheque_no_date_project_equipment_issued_at_installment_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Installment_1_expenditure_statement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Installment_2_expenditure_statement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Installment_3_expenditure_statement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Installment_4_expenditure_statement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
