# Generated by Django 4.2.1 on 2023-07-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARSProject', '0034_project_installment_1_expenditure_statement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cost_in_lakh',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_of_closure',
        ),
        migrations.AddField(
            model_name='project',
            name='closure_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
