# Generated by Django 4.2.1 on 2023-07-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CARSProject", "0036_alter_project_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
